
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Repo_Pattern_MVC_Model
{

using System;
    using System.Collections.Generic;
    
public partial class Form_Data_Master
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public string UserName { get; set; }

    public string Form_Data { get; set; }

}

}
